name: "assignment_dbt"
version: "1.0"
config-version: 2

profile: "assignment"

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  assignment_dbt:
    +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table
