# pytest.ini
[pytest]
pythonpath = /app
testpaths = /tests
addopts =
  --cov=/app
  --cov-report=term-missing
  --cov-report=html:/app/htmlcov
  --cov-report=xml:/app/coverage.xml
  --cov-fail-under=50